export { RegisterPageRoutes } from './PageRoutes.js';
export { RegisterHealthRoutes } from './HealthRoutes.js';
export { RegisterTemplateRoutes } from './TemplateRoutes.js';
export { RegisterDisplayConfigRoutes } from './DisplayConfigRoutes.js';
export { RegisterProjectionConfigRoutes } from './ProjectionConfigRoutes.js';
export { RegisterProjectionRoutes } from './ProjectionRoutes.js';
export { RegisterPreviewRoutes } from './PreviewRoutes.js';
export { RegisterGameRoutes } from './GameRoutes.js';
export { RegisterAuditRoutes } from './AuditRoutes.js';
export { RegisterMetricsRoutes } from './MetricsRoutes.js';
export type { IRouteContext } from './IRouteContext.js';
